openapi: "3.0.0"
info:
  version: 1.0.0
  title: MG poalim v1
  description: Population and Immigration Authority backend service used for Yael Google Apigee POC
  contact:
    name: Yael Software (Apigee)
    email: mosheg@yaelsoft.com
    url: https://yaelsoft.co.il
  license:
    name: private
    url: https://yaelsoft.co.il
servers:
  - url: "https://34.160.49.110.nip.io/v1/poalimmap"
    description: Client backend mapping
security:
  - api-key: []
paths:
  /citizens/{citizenId}:
    get:
      tags:
        - Citizen
      summary: Get a citizen details
      operationId: getCitizenById 
      responses:
        '200':
          description: Selected citizen
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Citizen"
        '404':
          description: Citizen not found
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Error"
        '403':
          description: Invalid ID
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Error"
      parameters:
        - name: citizenId
          in: path
          description: Citizen's id
          required: true
          schema:
            $ref: '#/components/schemas/Citizen/properties/IdNumber'
components:
  securitySchemes:
    api-key:
      type: apiKey
      name: api-key
      in: query
  schemas:
    Citizen:
      type: object
      description: citizen details
      properties:
        IdNumber:
          description: integer id (used for access)
          type: integer
          format: int32
          minimum: 0
        FirstName:
          description: citizen's first name
          type: string
        LastName:
          description: citizen's last name
          type: string
        CityName:
          description: the city which the citizen register in
          type: string
        StreetName:
          description: the street of the citizen
          type: string
        ZipCode7:
          description: citizen's zipcode (7)
          type: integer
          format: int32
    Error:
      type: object
      description: error response
      required:
        - error
        - error_description
      properties:
        error:
          type: string
        error_description:
          type: string